### ISSUE TITLE
0.3.1 New synced notes are listed as "blank space" in notes list first

### ISSUE THREAD

**Issue by Heart1010** [JackGruber/joplin-plugin-notelistpreview#10]
Don't know if the new 0.3.1 update causes this but never had these "blank space(s)" in the note list before.

I have to click the "blank space" so the note gets loaded (one by one) - after that everything is ok again.

![image](https://github.com/JackGruber/joplin-plugin-notelistpreview/assets/1481680/fd24bee2-e9d5-4d65-96ad-3ed9671bbb26)

**Comment by JackGruber** [comment]
The update `0.3.1` cannot have caused this, as this was only an update for the website without any plugin changes.
Was `0.2.0` installed before?

Does this occur with every Joplin start?

**Comment by Heart1010** [comment]
I think I already had `0.3.0` before installed the `0.3.1` update...
> Does this occur with every Joplin start?

When I have clicked that "blank space" one time so the note gets loaded everyting is ok. (so also after a joplin restart I don't have that blank space anymore for that note)

So you think something different causes this?
When I have those "blank spaces notes" there and I switch to Note list style > compact - I see the notes titles without any problems.
When I switch then back again to Note list style > preview - the totally blank space for that note changes to this (I can see the title now but no preview text or thumbnail)

![image](https://github.com/JackGruber/joplin-plugin-notelistpreview/assets/1481680/0694153f-5194-4037-a3b0-432cea0f02c7)

Is it because I use this "auto" setting for my synchronization? (but I think I haven't faced such blank notes in the past - but only using joplin for about a month)
![image](https://github.com/JackGruber/joplin-plugin-notelistpreview/assets/1481680/7c77f3fe-e382-449d-b9ae-df76e76c3eb2)

**Comment by JackGruber** [comment]
The `Attachment download behavior` could be the problem. 
I'll see if I can create a debug version today which you can test and then we might see more in the logs.

**Comment by JackGruber** [comment]
I was able to recreate the problem. Now, it no longer tries to create a preview of a resource that has not been downloaded
