### ISSUE TITLE
Plugin update not working

### ISSUE THREAD

**Issue by jlnmrc** [JackGruber/joplin-plugin-notelistpreview#11]
When I click Update, the button shows Updating then Updated and Joplin asks me to restart.
![image](https://github.com/JackGruber/joplin-plugin-notelistpreview/assets/14196859/aa3a353f-bb49-412a-b953-6b760552812c)

I restart and still have the v0.2.0 with the Update button.
![image](https://github.com/JackGruber/joplin-plugin-notelistpreview/assets/14196859/3231026a-5783-410f-aabc-80e98aec066d)

**Comment by JackGruber** [comment]
This has nothing to do with the plugin. 
Please create a topic for this in Support at https://discourse.joplinapp.org/
