### ISSUE TITLE
Broken image (webp) displayed

### ISSUE THREAD

**Issue by marph91** [JackGruber/joplin-plugin-notelistpreview#13]
I have a note with one image in the format `![alt](:/<ressource_id> "title")`. In the note list preview, only the "broken image icon" is displayed. When removing the title (`![alt](:/<ressource_id>)`), it's displayed correctly.

It would be nice to have support for images with title.

**Comment by JackGruber** [comment]
I cannot reproduce the problem. 
![grafik](https://github.com/JackGruber/joplin-plugin-notelistpreview/assets/24863925/3572e210-003c-4128-8718-722393016285)

Are you using the latest plugin version or still 0.2.0 or less?

**Comment by marph91** [comment]
I'm on plugin version 0.3.2 and Joplin 2.14.10.

Did you add the title before or after the thumbnail (in the note list preview) was created? I just tested it and it seems the bug only occurs if the title is there before the thumbnail was created.

If the title is added after the first rendering of the note list preview, the image is always displayed correctly. Even after a reboot. Maybe this is related to caching?

**Edit**: Can be reproduced by using the webclipper ("Clip complete page (Markdown)") on [this page](https://www.nationalgeographic.de/geschichte-und-kultur/2023/07/wikinger-hamburg-ueberfall-deutschland-archaeologie).

**Comment by JackGruber** [comment]
>Maybe this is related to caching?

The cache is regenerated on every Joplin start. 
Only valid resources for which an image operation can be performed should be displayed. 

>Edit: Can be reproduced by using the webclipper ("Clip complete page (Markdown)") .... 
I don't have a web clipper running, I'm not sure if I want to install it

However, you can also attach a JEX export of the note and a screenshot of the error.
Is there some error in the Joplin log?

**Comment by marph91** [comment]
Here is a (shortened) version of the note (needed to zip in order to upload it): [Als die Wikinger in Hamburg einfielen _ National Geographic.zip](https://github.com/JackGruber/joplin-plugin-notelistpreview/files/14002837/Als.die.Wikinger.in.Hamburg.einfielen._.National.Geographic.zip)

and the corresponding screenshot:

![Screenshot_20240121_221652](https://github.com/JackGruber/joplin-plugin-notelistpreview/assets/33229141/2f61ea10-828f-4001-bc4c-6957c19f43dc)

I couldn't see any specific error message related to this plugin.

**Comment by JackGruber** [comment]
Ok, I think the problem is that the image is a `webp`, I'll need to check this, but looks like the Joplin image lib can't handel this file format

**Comment by marph91** [comment]
Thanks for investigating and fixing! I can confirm that there are no broken thumbnails with version 0.4.0.

Is there any chance that `webp` images get displayed? Probably the [joplin image lib](https://joplinapp.org/api/references/plugin_api/classes/joplinimaging.html) would need to be extended by `webp`?

**Comment by JackGruber** [comment]
I was already in contact with laurent and we will check if the used libs in Joplin can support webp
