### ISSUE TITLE
Confidential notes

### ISSUE THREAD

**Issue by lzambarda** [JackGruber/joplin-plugin-notelistpreview#17]
Hi there, first of all thanks for the excellent plugin. It has really enhanced my experience with Joplin!

I have some notes with "sensitive" content and it is not ideal to have a preview of them appearing in the note list. I was thinking that it would be nice to omit the preview or have a placeholder for such notes, perhaps a tag could be used to mark which notes are sensitive.

Thank you!

**Comment by JackGruber** [comment]
Yes, could possibly be implement with tags and note settings (context menu). 
I will give it some thought.

Mock of the preview with confidential note: 
![grafik](https://github.com/JackGruber/joplin-plugin-notelistpreview/assets/24863925/8913c7bc-6066-4024-a1d3-17067ebed44b)


- Display no images
- Display no tags
- Replace text

**Comment by lzambarda** [comment]
This is exactly what I was thinking about! (also, das Mock sieht gut aus 😄 )
