### ISSUE TITLE
Feature request: Allow increasing resolution of preview images

### ISSUE THREAD

**Issue by personalizedrefrigerator** [JackGruber/joplin-plugin-notelistpreview#18]
At present, preview images can be blurry, particularly at high zoom levels (see [upstream issue](https://github.com/laurent22/joplin/issues/9796)).

This seems to be less of an issue if images are resized to a larger size before converting to JPEG. For example, resizing to 150px × 150px for a 75px × 75px preview.

**Comment by JackGruber** [comment]
Do you know if there is a option to read the actual zoom level from Joplin?

**Comment by personalizedrefrigerator** [comment]
I think `joplin.settings.globalValue("windowContentZoomFactor")` should return Joplin's zoom level (30% - 300%).

Alternatively, [`window.devicePixelRatio`](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio), **when run from a content script**, should return a conversion factor between "px" units and screen pixels. Note that `devicePixelRatio` depends on a user's display resolution while `windowContentZoomFactor` does not.
