### ISSUE TITLE
Cant't install on Joplin 2.14.20 (desktop windows)

### ISSUE THREAD

**Issue by sweetman-zz** [JackGruber/joplin-plugin-notelistpreview#26]
Hello all, 
I would like to install this plugin but I can't because It needs me to update Joplin (I have installed Joplin 2.14.20 on windows 10, desktop).
![2024-05-02 17-29-19](https://github.com/JackGruber/joplin-plugin-notelistpreview/assets/2510140/0511b664-17ee-42e8-80a9-44b972a39540)
Perhaps I need to install a dev release?
TIA
Tony

**Comment by JackGruber** [comment]
You need to install the Plugin version [v0.4.2](https://github.com/JackGruber/joplin-plugin-notelistpreview/releases/tag/v0.4.2), this is possible via [manual install](https://github.com/JackGruber/joplin-plugin-notelistpreview?tab=readme-ov-file#manual). 
All newer versions need a Joplin version off minimum of `3.0.3`

**Comment by sweetman-zz** [comment]
ok, thanks
