### ISSUE TITLE
The plugin is not working on Joplin 2.14.22 Mac M1

### ISSUE THREAD

**Issue by iavitech** [JackGruber/joplin-plugin-notelistpreview#27]
Hello, the plugin is not working on Joplin 2.14.22 for Mac M1.

In plugins section the plugin is disabled, and appears the message: "Please upgrade Joplin to use this plugin."
* I already have the last Joplin version( 2.14.22 for Mac M1)

<img width="628" alt="Screenshot 2024-05-25 at 9 23 36" src="https://github.com/JackGruber/joplin-plugin-notelistpreview/assets/50178002/5b654145-519d-4937-9396-36b6b6113092">

<img width="451" alt="Screenshot 2024-05-25 at 9 24 08" src="https://github.com/JackGruber/joplin-plugin-notelistpreview/assets/50178002/1bdc59c7-35ee-4513-894e-b8b49b87df0a">

**Comment by JackGruber** [comment]
Follow the instructions from: https://github.com/JackGruber/joplin-plugin-notelistpreview/issues/26
