### ISSUE TITLE
Item height based on content (auto)

### ISSUE THREAD

**Issue by ivangretsky** [JackGruber/joplin-plugin-notelistpreview#31]
Good day and thanks for the super plugin!

Is it now possible and if not is it possible to add a preview item height based on the content height? Like a default html behavior? No need to guess and set pixels... I've tried set Item height to 0, but they just disappeared.

**Comment by JackGruber** [comment]
No this is not possible, the item height is always fixed, as this is required for loading and rendering the item in joplin.

**Comment by ivangretsky** [comment]
Thanks for your response! Could you please lead me to the info about the need for a fixed item height? I've tried to play around with the dev tools, and it seemed ok. I couldn't test all cases for sure...

**Comment by JackGruber** [comment]
- https://joplinapp.org/api/references/plugin_api/classes/joplinviewsnotelist.html#registerrenderer
- https://joplinapp.org/api/references/plugin_api/interfaces/listrenderer.html#itemsize

**Comment by ivangretsky** [comment]
Thanks! Have you tried ignoring the itemsize? Just for the case when one is ok with performance penalties? Or is it mandatory to set and type checked?
