### ISSUE TITLE
How to style the preview with css?

### ISSUE THREAD

**Issue by ivangretsky** [JackGruber/joplin-plugin-notelistpreview#34]
Hi! I am finding this plugin more and more useful! Thanks!

Is there a way to style the previews with css? Joplin has custom css table option. This would probably work. But is there a class list for styling or something?

**Comment by JackGruber** [comment]
Use the develop tools to inspect the elements. There are many entries on the CSS topic in the Joplin forum. 
Example of one element:
![image](https://github.com/user-attachments/assets/93bd76e9-e438-4ee9-8091-dc1e8897ee4b)

**Comment by ivangretsky** [comment]
Thanks. Will do that.
